services:
  app:
    build: .
    container_name: estetica-app
    image: estetica-app
    ports:
      - 3000:3000
    restart: unless-stopped

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
